<?php

/**
 * @file
 * Varbase Vartheme Claro.
 *
 * Have custom alteration over the theme layer.
 */

use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function vartheme_claro_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if (is_numeric($node)) {
      $node = Node::load($node);
    }
    if ($node instanceof NodeInterface) {
      array_splice($suggestions, 1, 0, 'page__' . $node->bundle());
    }
  }
}

/**
 * Implements hook_library_info_alter().
 */
function vartheme_claro_library_info_alter(&$libraries, $extension) {

  if ($extension === 'ckeditor' && version_compare(Drupal::VERSION, '10.0.0', '<')) {

    // Extend claro/ckeditor-editor with the ckeditor/drupal.ckeditor library.
    if (isset($libraries['drupal.ckeditor'])) {
      $libraries['drupal.ckeditor']['dependencies'][] = 'claro/ckeditor-editor';
    }

    // Extend ckeditor/drupal.ckeditor.admin with the claro/ckeditor-admin library.
    if (isset($libraries['drupal.ckeditor.admin'])) {
      $libraries['drupal.ckeditor.admin']['dependencies'][] = 'claro/ckeditor-admin';
    }

    // Extend ckeditor/ckeditor with the claro/ckeditor-dialog library.
    if (isset($libraries['ckeditor'])) {
      $libraries['ckeditor']['dependencies'][] = 'claro/ckeditor-dialog';
    }
  }

  if ($extension === 'core' && version_compare(Drupal::VERSION, '10.0.0', '<')) {

    // Extend core/ckeditor with the claro/ckeditor-dialog library.
    if (isset($libraries['ckeditor'])) {
      $libraries['ckeditor']['dependencies'][] = 'claro/ckeditor-dialog';
    }
  }

  if ($extension === 'claro') {
    if (version_compare(Drupal::VERSION, '10.0.0', '<')) {
      if (isset($libraries['global-styling'])) {
        $libraries['global-styling']['dependencies'][] = 'vartheme_claro/claro9.layout-node-form';
      }
    }
    else {
      if (isset($libraries['global-styling'])) {
        $libraries['global-styling']['dependencies'][] = 'vartheme_claro/claro10.layout-node-form';
      }
    }
  }
}
